// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/cluster/proto/sentinel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // one-time enrollment token
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"` // human-readable agent label
	Csr           []byte                 `protobuf:"bytes,3,opt,name=csr,proto3" json:"csr,omitempty"`                           // PKCS#10 certificate signing request (DER)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *EnrollRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CaCert        []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`          // CA certificate PEM
	AgentCert     []byte                 `protobuf:"bytes,3,opt,name=agent_cert,json=agentCert,proto3" json:"agent_cert,omitempty"` // signed agent certificate PEM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *EnrollResponse) GetAgentCert() []byte {
	if x != nil {
		return x.AgentCert
	}
	return nil
}

// AgentMessage is a wrapper for all agent-to-server stream messages.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ContainerList
	//	*AgentMessage_UpdateResult
	//	*AgentMessage_HookResult
	//	*AgentMessage_RollbackResult
	//	*AgentMessage_OfflineJournal
	//	*AgentMessage_CertRenewal
	//	*AgentMessage_ContainerActionResult
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{2}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerList() *ContainerList {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerList); ok {
			return x.ContainerList
		}
	}
	return nil
}

func (x *AgentMessage) GetUpdateResult() *UpdateResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_UpdateResult); ok {
			return x.UpdateResult
		}
	}
	return nil
}

func (x *AgentMessage) GetHookResult() *HookResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_HookResult); ok {
			return x.HookResult
		}
	}
	return nil
}

func (x *AgentMessage) GetRollbackResult() *RollbackResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_RollbackResult); ok {
			return x.RollbackResult
		}
	}
	return nil
}

func (x *AgentMessage) GetOfflineJournal() *OfflineJournal {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_OfflineJournal); ok {
			return x.OfflineJournal
		}
	}
	return nil
}

func (x *AgentMessage) GetCertRenewal() *CertRenewalCSR {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CertRenewal); ok {
			return x.CertRenewal
		}
	}
	return nil
}

func (x *AgentMessage) GetContainerActionResult() *ContainerActionResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ContainerActionResult); ok {
			return x.ContainerActionResult
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ContainerList struct {
	ContainerList *ContainerList `protobuf:"bytes,2,opt,name=container_list,json=containerList,proto3,oneof"`
}

type AgentMessage_UpdateResult struct {
	UpdateResult *UpdateResult `protobuf:"bytes,3,opt,name=update_result,json=updateResult,proto3,oneof"`
}

type AgentMessage_HookResult struct {
	HookResult *HookResult `protobuf:"bytes,4,opt,name=hook_result,json=hookResult,proto3,oneof"`
}

type AgentMessage_RollbackResult struct {
	RollbackResult *RollbackResult `protobuf:"bytes,5,opt,name=rollback_result,json=rollbackResult,proto3,oneof"`
}

type AgentMessage_OfflineJournal struct {
	OfflineJournal *OfflineJournal `protobuf:"bytes,6,opt,name=offline_journal,json=offlineJournal,proto3,oneof"`
}

type AgentMessage_CertRenewal struct {
	CertRenewal *CertRenewalCSR `protobuf:"bytes,7,opt,name=cert_renewal,json=certRenewal,proto3,oneof"`
}

type AgentMessage_ContainerActionResult struct {
	ContainerActionResult *ContainerActionResult `protobuf:"bytes,8,opt,name=container_action_result,json=containerActionResult,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerList) isAgentMessage_Payload() {}

func (*AgentMessage_UpdateResult) isAgentMessage_Payload() {}

func (*AgentMessage_HookResult) isAgentMessage_Payload() {}

func (*AgentMessage_RollbackResult) isAgentMessage_Payload() {}

func (*AgentMessage_OfflineJournal) isAgentMessage_Payload() {}

func (*AgentMessage_CertRenewal) isAgentMessage_Payload() {}

func (*AgentMessage_ContainerActionResult) isAgentMessage_Payload() {}

// ServerMessage is a wrapper for all server-to-agent stream messages.
type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // unique ID for idempotency + correlation
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Heartbeat
	//	*ServerMessage_ListContainers
	//	*ServerMessage_UpdateContainer
	//	*ServerMessage_PullImage
	//	*ServerMessage_RunHook
	//	*ServerMessage_Rollback
	//	*ServerMessage_PolicySync
	//	*ServerMessage_SettingsSync
	//	*ServerMessage_CertRenewalResponse
	//	*ServerMessage_ContainerAction
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerMessage) GetListContainers() *ListContainersRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ListContainers); ok {
			return x.ListContainers
		}
	}
	return nil
}

func (x *ServerMessage) GetUpdateContainer() *UpdateContainerRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_UpdateContainer); ok {
			return x.UpdateContainer
		}
	}
	return nil
}

func (x *ServerMessage) GetPullImage() *PullImageRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PullImage); ok {
			return x.PullImage
		}
	}
	return nil
}

func (x *ServerMessage) GetRunHook() *RunHookRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_RunHook); ok {
			return x.RunHook
		}
	}
	return nil
}

func (x *ServerMessage) GetRollback() *RollbackRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Rollback); ok {
			return x.Rollback
		}
	}
	return nil
}

func (x *ServerMessage) GetPolicySync() *PolicySync {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PolicySync); ok {
			return x.PolicySync
		}
	}
	return nil
}

func (x *ServerMessage) GetSettingsSync() *SettingsSync {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SettingsSync); ok {
			return x.SettingsSync
		}
	}
	return nil
}

func (x *ServerMessage) GetCertRenewalResponse() *CertRenewalResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_CertRenewalResponse); ok {
			return x.CertRenewalResponse
		}
	}
	return nil
}

func (x *ServerMessage) GetContainerAction() *ContainerActionRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_ContainerAction); ok {
			return x.ContainerAction
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ServerMessage_ListContainers struct {
	ListContainers *ListContainersRequest `protobuf:"bytes,3,opt,name=list_containers,json=listContainers,proto3,oneof"`
}

type ServerMessage_UpdateContainer struct {
	UpdateContainer *UpdateContainerRequest `protobuf:"bytes,4,opt,name=update_container,json=updateContainer,proto3,oneof"`
}

type ServerMessage_PullImage struct {
	PullImage *PullImageRequest `protobuf:"bytes,5,opt,name=pull_image,json=pullImage,proto3,oneof"`
}

type ServerMessage_RunHook struct {
	RunHook *RunHookRequest `protobuf:"bytes,6,opt,name=run_hook,json=runHook,proto3,oneof"`
}

type ServerMessage_Rollback struct {
	Rollback *RollbackRequest `protobuf:"bytes,7,opt,name=rollback,proto3,oneof"`
}

type ServerMessage_PolicySync struct {
	PolicySync *PolicySync `protobuf:"bytes,8,opt,name=policy_sync,json=policySync,proto3,oneof"`
}

type ServerMessage_SettingsSync struct {
	SettingsSync *SettingsSync `protobuf:"bytes,9,opt,name=settings_sync,json=settingsSync,proto3,oneof"`
}

type ServerMessage_CertRenewalResponse struct {
	CertRenewalResponse *CertRenewalResponse `protobuf:"bytes,10,opt,name=cert_renewal_response,json=certRenewalResponse,proto3,oneof"`
}

type ServerMessage_ContainerAction struct {
	ContainerAction *ContainerActionRequest `protobuf:"bytes,11,opt,name=container_action,json=containerAction,proto3,oneof"`
}

func (*ServerMessage_Heartbeat) isServerMessage_Payload() {}

func (*ServerMessage_ListContainers) isServerMessage_Payload() {}

func (*ServerMessage_UpdateContainer) isServerMessage_Payload() {}

func (*ServerMessage_PullImage) isServerMessage_Payload() {}

func (*ServerMessage_RunHook) isServerMessage_Payload() {}

func (*ServerMessage_Rollback) isServerMessage_Payload() {}

func (*ServerMessage_PolicySync) isServerMessage_Payload() {}

func (*ServerMessage_SettingsSync) isServerMessage_Payload() {}

func (*ServerMessage_CertRenewalResponse) isServerMessage_Payload() {}

func (*ServerMessage_ContainerAction) isServerMessage_Payload() {}

type Heartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                // semver of agent binary
	SupportedFeatures []string               `protobuf:"bytes,3,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"` // capability negotiation
	HostId            string                 `protobuf:"bytes,4,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`                                  // identifies which agent
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Heartbeat) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Heartbeat) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *Heartbeat) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                // full image reference (e.g. "nginx:1.25")
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"` // currently running digest
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                // "running", "stopped", etc.
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerInfo) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type ContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // echoes the server's request_id
	Containers    []*ContainerInfo       `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerList) Reset() {
	*x = ContainerList{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerList) ProtoMessage() {}

func (x *ContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerList.ProtoReflect.Descriptor instead.
func (*ContainerList) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerList) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ContainerList) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{7}
}

type UpdateContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	TargetImage   string                 `protobuf:"bytes,2,opt,name=target_image,json=targetImage,proto3" json:"target_image,omitempty"`    // image reference to update to
	TargetDigest  string                 `protobuf:"bytes,3,opt,name=target_digest,json=targetDigest,proto3" json:"target_digest,omitempty"` // expected digest of the new image
	SkipHooks     bool                   `protobuf:"varint,4,opt,name=skip_hooks,json=skipHooks,proto3" json:"skip_hooks,omitempty"`         // skip pre/post-update hooks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContainerRequest) Reset() {
	*x = UpdateContainerRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContainerRequest) ProtoMessage() {}

func (x *UpdateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContainerRequest.ProtoReflect.Descriptor instead.
func (*UpdateContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateContainerRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *UpdateContainerRequest) GetTargetImage() string {
	if x != nil {
		return x.TargetImage
	}
	return ""
}

func (x *UpdateContainerRequest) GetTargetDigest() string {
	if x != nil {
		return x.TargetDigest
	}
	return ""
}

func (x *UpdateContainerRequest) GetSkipHooks() bool {
	if x != nil {
		return x.SkipHooks
	}
	return false
}

type ContainerActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "stop", "start", "restart"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerActionRequest) Reset() {
	*x = ContainerActionRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerActionRequest) ProtoMessage() {}

func (x *ContainerActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerActionRequest.ProtoReflect.Descriptor instead.
func (*ContainerActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerActionRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ContainerActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Outcome       string                 `protobuf:"bytes,4,opt,name=outcome,proto3" json:"outcome,omitempty"` // "success" or "failed"
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerActionResult) Reset() {
	*x = ContainerActionResult{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerActionResult) ProtoMessage() {}

func (x *ContainerActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerActionResult.ProtoReflect.Descriptor instead.
func (*ContainerActionResult) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerActionResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ContainerActionResult) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerActionResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ContainerActionResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ContainerActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // echoes the server's request_id
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	OldImage      string                 `protobuf:"bytes,3,opt,name=old_image,json=oldImage,proto3" json:"old_image,omitempty"`
	OldDigest     string                 `protobuf:"bytes,4,opt,name=old_digest,json=oldDigest,proto3" json:"old_digest,omitempty"`
	NewImage      string                 `protobuf:"bytes,5,opt,name=new_image,json=newImage,proto3" json:"new_image,omitempty"`
	NewDigest     string                 `protobuf:"bytes,6,opt,name=new_digest,json=newDigest,proto3" json:"new_digest,omitempty"`
	Outcome       string                 `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"` // "success", "rollback", "failed"
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,9,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResult) Reset() {
	*x = UpdateResult{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResult) ProtoMessage() {}

func (x *UpdateResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResult.ProtoReflect.Descriptor instead.
func (*UpdateResult) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateResult) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *UpdateResult) GetOldImage() string {
	if x != nil {
		return x.OldImage
	}
	return ""
}

func (x *UpdateResult) GetOldDigest() string {
	if x != nil {
		return x.OldDigest
	}
	return ""
}

func (x *UpdateResult) GetNewImage() string {
	if x != nil {
		return x.NewImage
	}
	return ""
}

func (x *UpdateResult) GetNewDigest() string {
	if x != nil {
		return x.NewDigest
	}
	return ""
}

func (x *UpdateResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *UpdateResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateResult) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type PullImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"` // image to pull (e.g. "nginx:1.26")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{12}
}

func (x *PullImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type RunHookRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerName  string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // "pre-update" or "post-update"
	Command        string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunHookRequest) Reset() {
	*x = RunHookRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunHookRequest) ProtoMessage() {}

func (x *RunHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunHookRequest.ProtoReflect.Descriptor instead.
func (*RunHookRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{13}
}

func (x *RunHookRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RunHookRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *RunHookRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *RunHookRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type HookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{14}
}

func (x *HookResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HookResult) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *HookResult) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *HookResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *HookResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *HookResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerName string                 `protobuf:"bytes,1,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{15}
}

func (x *RollbackRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type RollbackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"` // "success" or "failed"
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResult) Reset() {
	*x = RollbackResult{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResult) ProtoMessage() {}

func (x *RollbackResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResult.ProtoReflect.Descriptor instead.
func (*RollbackResult) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{16}
}

func (x *RollbackResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RollbackResult) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RollbackResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *RollbackResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StateReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HostId            string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Containers        []*ContainerInfo       `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentVersion      string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,5,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StateReport) Reset() {
	*x = StateReport{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateReport) ProtoMessage() {}

func (x *StateReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateReport.ProtoReflect.Descriptor instead.
func (*StateReport) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{17}
}

func (x *StateReport) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *StateReport) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *StateReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StateReport) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *StateReport) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

type StateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // e.g. "state received" or error detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateAck) Reset() {
	*x = StateAck{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateAck) ProtoMessage() {}

func (x *StateAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateAck.ProtoReflect.Descriptor instead.
func (*StateAck) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{18}
}

func (x *StateAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StateAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PolicySync struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-container policy overrides pushed from server to agent.
	Policies      map[string]string `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // container_name -> "auto"/"manual"/"pinned"
	DefaultPolicy string            `protobuf:"bytes,2,opt,name=default_policy,json=defaultPolicy,proto3" json:"default_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicySync) Reset() {
	*x = PolicySync{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySync) ProtoMessage() {}

func (x *PolicySync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySync.ProtoReflect.Descriptor instead.
func (*PolicySync) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{19}
}

func (x *PolicySync) GetPolicies() map[string]string {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *PolicySync) GetDefaultPolicy() string {
	if x != nil {
		return x.DefaultPolicy
	}
	return ""
}

type SettingsSync struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PollInterval     *durationpb.Duration   `protobuf:"bytes,1,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	GracePeriod      *durationpb.Duration   `protobuf:"bytes,2,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	LatestAutoUpdate bool                   `protobuf:"varint,3,opt,name=latest_auto_update,json=latestAutoUpdate,proto3" json:"latest_auto_update,omitempty"`
	ImageCleanup     bool                   `protobuf:"varint,4,opt,name=image_cleanup,json=imageCleanup,proto3" json:"image_cleanup,omitempty"`
	HooksEnabled     bool                   `protobuf:"varint,5,opt,name=hooks_enabled,json=hooksEnabled,proto3" json:"hooks_enabled,omitempty"`
	DependencyAware  bool                   `protobuf:"varint,6,opt,name=dependency_aware,json=dependencyAware,proto3" json:"dependency_aware,omitempty"`
	RollbackPolicy   string                 `protobuf:"bytes,7,opt,name=rollback_policy,json=rollbackPolicy,proto3" json:"rollback_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SettingsSync) Reset() {
	*x = SettingsSync{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSync) ProtoMessage() {}

func (x *SettingsSync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsSync.ProtoReflect.Descriptor instead.
func (*SettingsSync) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{20}
}

func (x *SettingsSync) GetPollInterval() *durationpb.Duration {
	if x != nil {
		return x.PollInterval
	}
	return nil
}

func (x *SettingsSync) GetGracePeriod() *durationpb.Duration {
	if x != nil {
		return x.GracePeriod
	}
	return nil
}

func (x *SettingsSync) GetLatestAutoUpdate() bool {
	if x != nil {
		return x.LatestAutoUpdate
	}
	return false
}

func (x *SettingsSync) GetImageCleanup() bool {
	if x != nil {
		return x.ImageCleanup
	}
	return false
}

func (x *SettingsSync) GetHooksEnabled() bool {
	if x != nil {
		return x.HooksEnabled
	}
	return false
}

func (x *SettingsSync) GetDependencyAware() bool {
	if x != nil {
		return x.DependencyAware
	}
	return false
}

func (x *SettingsSync) GetRollbackPolicy() string {
	if x != nil {
		return x.RollbackPolicy
	}
	return ""
}

type OfflineJournal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*JournalEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineJournal) Reset() {
	*x = OfflineJournal{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineJournal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineJournal) ProtoMessage() {}

func (x *OfflineJournal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineJournal.ProtoReflect.Descriptor instead.
func (*OfflineJournal) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{21}
}

func (x *OfflineJournal) GetEntries() []*JournalEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type JournalEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "update", "rollback", "hook"
	Container     string                 `protobuf:"bytes,4,opt,name=container,proto3" json:"container,omitempty"`
	OldImage      string                 `protobuf:"bytes,5,opt,name=old_image,json=oldImage,proto3" json:"old_image,omitempty"`
	NewImage      string                 `protobuf:"bytes,6,opt,name=new_image,json=newImage,proto3" json:"new_image,omitempty"`
	OldDigest     string                 `protobuf:"bytes,7,opt,name=old_digest,json=oldDigest,proto3" json:"old_digest,omitempty"`
	NewDigest     string                 `protobuf:"bytes,8,opt,name=new_digest,json=newDigest,proto3" json:"new_digest,omitempty"`
	Outcome       string                 `protobuf:"bytes,9,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,11,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{22}
}

func (x *JournalEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JournalEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *JournalEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *JournalEntry) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *JournalEntry) GetOldImage() string {
	if x != nil {
		return x.OldImage
	}
	return ""
}

func (x *JournalEntry) GetNewImage() string {
	if x != nil {
		return x.NewImage
	}
	return ""
}

func (x *JournalEntry) GetOldDigest() string {
	if x != nil {
		return x.OldDigest
	}
	return ""
}

func (x *JournalEntry) GetNewDigest() string {
	if x != nil {
		return x.NewDigest
	}
	return ""
}

func (x *JournalEntry) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *JournalEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JournalEntry) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type CertRenewalCSR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Csr           []byte                 `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"` // new PKCS#10 CSR (DER)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewalCSR) Reset() {
	*x = CertRenewalCSR{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewalCSR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewalCSR) ProtoMessage() {}

func (x *CertRenewalCSR) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewalCSR.ProtoReflect.Descriptor instead.
func (*CertRenewalCSR) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{23}
}

func (x *CertRenewalCSR) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type CertRenewalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentCert     []byte                 `protobuf:"bytes,1,opt,name=agent_cert,json=agentCert,proto3" json:"agent_cert,omitempty"` // newly signed certificate PEM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewalResponse) Reset() {
	*x = CertRenewalResponse{}
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewalResponse) ProtoMessage() {}

func (x *CertRenewalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_cluster_proto_sentinel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewalResponse.ProtoReflect.Descriptor instead.
func (*CertRenewalResponse) Descriptor() ([]byte, []int) {
	return file_internal_cluster_proto_sentinel_proto_rawDescGZIP(), []int{24}
}

func (x *CertRenewalResponse) GetAgentCert() []byte {
	if x != nil {
		return x.AgentCert
	}
	return nil
}

var File_internal_cluster_proto_sentinel_proto protoreflect.FileDescriptor

const file_internal_cluster_proto_sentinel_proto_rawDesc = "" +
	"\n" +
	"%internal/cluster/proto/sentinel.proto\x12\x10sentinel.cluster\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"T\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x10\n" +
	"\x03csr\x18\x03 \x01(\fR\x03csr\"a\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12\x1d\n" +
	"\n" +
	"agent_cert\x18\x03 \x01(\fR\tagentCert\"\xec\x04\n" +
	"\fAgentMessage\x12;\n" +
	"\theartbeat\x18\x01 \x01(\v2\x1b.sentinel.cluster.HeartbeatH\x00R\theartbeat\x12H\n" +
	"\x0econtainer_list\x18\x02 \x01(\v2\x1f.sentinel.cluster.ContainerListH\x00R\rcontainerList\x12E\n" +
	"\rupdate_result\x18\x03 \x01(\v2\x1e.sentinel.cluster.UpdateResultH\x00R\fupdateResult\x12?\n" +
	"\vhook_result\x18\x04 \x01(\v2\x1c.sentinel.cluster.HookResultH\x00R\n" +
	"hookResult\x12K\n" +
	"\x0frollback_result\x18\x05 \x01(\v2 .sentinel.cluster.RollbackResultH\x00R\x0erollbackResult\x12K\n" +
	"\x0foffline_journal\x18\x06 \x01(\v2 .sentinel.cluster.OfflineJournalH\x00R\x0eofflineJournal\x12E\n" +
	"\fcert_renewal\x18\a \x01(\v2 .sentinel.cluster.CertRenewalCSRH\x00R\vcertRenewal\x12a\n" +
	"\x17container_action_result\x18\b \x01(\v2'.sentinel.cluster.ContainerActionResultH\x00R\x15containerActionResultB\t\n" +
	"\apayload\"\xa2\x06\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1b.sentinel.cluster.HeartbeatH\x00R\theartbeat\x12R\n" +
	"\x0flist_containers\x18\x03 \x01(\v2'.sentinel.cluster.ListContainersRequestH\x00R\x0elistContainers\x12U\n" +
	"\x10update_container\x18\x04 \x01(\v2(.sentinel.cluster.UpdateContainerRequestH\x00R\x0fupdateContainer\x12C\n" +
	"\n" +
	"pull_image\x18\x05 \x01(\v2\".sentinel.cluster.PullImageRequestH\x00R\tpullImage\x12=\n" +
	"\brun_hook\x18\x06 \x01(\v2 .sentinel.cluster.RunHookRequestH\x00R\arunHook\x12?\n" +
	"\brollback\x18\a \x01(\v2!.sentinel.cluster.RollbackRequestH\x00R\brollback\x12?\n" +
	"\vpolicy_sync\x18\b \x01(\v2\x1c.sentinel.cluster.PolicySyncH\x00R\n" +
	"policySync\x12E\n" +
	"\rsettings_sync\x18\t \x01(\v2\x1e.sentinel.cluster.SettingsSyncH\x00R\fsettingsSync\x12[\n" +
	"\x15cert_renewal_response\x18\n" +
	" \x01(\v2%.sentinel.cluster.CertRenewalResponseH\x00R\x13certRenewalResponse\x12U\n" +
	"\x10container_action\x18\v \x01(\v2(.sentinel.cluster.ContainerActionRequestH\x00R\x0fcontainerActionB\t\n" +
	"\apayload\"\xb2\x01\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12-\n" +
	"\x12supported_features\x18\x03 \x03(\tR\x11supportedFeatures\x12\x17\n" +
	"\ahost_id\x18\x04 \x01(\tR\x06hostId\"\xb8\x02\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12C\n" +
	"\x06labels\x18\x06 \x03(\v2+.sentinel.cluster.ContainerInfo.LabelsEntryR\x06labels\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\rContainerList\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12?\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x1f.sentinel.cluster.ContainerInfoR\n" +
	"containers\"\x17\n" +
	"\x15ListContainersRequest\"\xa6\x01\n" +
	"\x16UpdateContainerRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12!\n" +
	"\ftarget_image\x18\x02 \x01(\tR\vtargetImage\x12#\n" +
	"\rtarget_digest\x18\x03 \x01(\tR\ftargetDigest\x12\x1d\n" +
	"\n" +
	"skip_hooks\x18\x04 \x01(\bR\tskipHooks\"W\n" +
	"\x16ContainerActionRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xa5\x01\n" +
	"\x15ContainerActionResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x04 \x01(\tR\aoutcome\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xb3\x02\n" +
	"\fUpdateResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x1b\n" +
	"\told_image\x18\x03 \x01(\tR\boldImage\x12\x1d\n" +
	"\n" +
	"old_digest\x18\x04 \x01(\tR\toldDigest\x12\x1b\n" +
	"\tnew_image\x18\x05 \x01(\tR\bnewImage\x12\x1d\n" +
	"\n" +
	"new_digest\x18\x06 \x01(\tR\tnewDigest\x12\x18\n" +
	"\aoutcome\x18\a \x01(\tR\aoutcome\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x125\n" +
	"\bduration\x18\t \x01(\v2\x19.google.protobuf.DurationR\bduration\"/\n" +
	"\x10PullImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\"\x90\x01\n" +
	"\x0eRunHookRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\xb3\x01\n" +
	"\n" +
	"HookResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"8\n" +
	"\x0fRollbackRequest\x12%\n" +
	"\x0econtainer_name\x18\x01 \x01(\tR\rcontainerName\"\x86\x01\n" +
	"\x0eRollbackResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf5\x01\n" +
	"\vStateReport\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12?\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x1f.sentinel.cluster.ContainerInfoR\n" +
	"containers\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12-\n" +
	"\x12supported_features\x18\x05 \x03(\tR\x11supportedFeatures\"@\n" +
	"\bStateAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb8\x01\n" +
	"\n" +
	"PolicySync\x12F\n" +
	"\bpolicies\x18\x01 \x03(\v2*.sentinel.cluster.PolicySync.PoliciesEntryR\bpolicies\x12%\n" +
	"\x0edefault_policy\x18\x02 \x01(\tR\rdefaultPolicy\x1a;\n" +
	"\rPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd8\x02\n" +
	"\fSettingsSync\x12>\n" +
	"\rpoll_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\fpollInterval\x12<\n" +
	"\fgrace_period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vgracePeriod\x12,\n" +
	"\x12latest_auto_update\x18\x03 \x01(\bR\x10latestAutoUpdate\x12#\n" +
	"\rimage_cleanup\x18\x04 \x01(\bR\fimageCleanup\x12#\n" +
	"\rhooks_enabled\x18\x05 \x01(\bR\fhooksEnabled\x12)\n" +
	"\x10dependency_aware\x18\x06 \x01(\bR\x0fdependencyAware\x12'\n" +
	"\x0frollback_policy\x18\a \x01(\tR\x0erollbackPolicy\"J\n" +
	"\x0eOfflineJournal\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.sentinel.cluster.JournalEntryR\aentries\"\xed\x02\n" +
	"\fJournalEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1c\n" +
	"\tcontainer\x18\x04 \x01(\tR\tcontainer\x12\x1b\n" +
	"\told_image\x18\x05 \x01(\tR\boldImage\x12\x1b\n" +
	"\tnew_image\x18\x06 \x01(\tR\bnewImage\x12\x1d\n" +
	"\n" +
	"old_digest\x18\a \x01(\tR\toldDigest\x12\x1d\n" +
	"\n" +
	"new_digest\x18\b \x01(\tR\tnewDigest\x12\x18\n" +
	"\aoutcome\x18\t \x01(\tR\aoutcome\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x125\n" +
	"\bduration\x18\v \x01(\v2\x19.google.protobuf.DurationR\bduration\"\"\n" +
	"\x0eCertRenewalCSR\x12\x10\n" +
	"\x03csr\x18\x01 \x01(\fR\x03csr\"4\n" +
	"\x13CertRenewalResponse\x12\x1d\n" +
	"\n" +
	"agent_cert\x18\x01 \x01(\fR\tagentCert2`\n" +
	"\x11EnrollmentService\x12K\n" +
	"\x06Enroll\x12\x1f.sentinel.cluster.EnrollRequest\x1a .sentinel.cluster.EnrollResponse2\xa8\x01\n" +
	"\fAgentService\x12N\n" +
	"\aChannel\x12\x1e.sentinel.cluster.AgentMessage\x1a\x1f.sentinel.cluster.ServerMessage(\x010\x01\x12H\n" +
	"\vReportState\x12\x1d.sentinel.cluster.StateReport\x1a\x1a.sentinel.cluster.StateAckB=Z;github.com/Will-Luck/Docker-Sentinel/internal/cluster/protob\x06proto3"

var (
	file_internal_cluster_proto_sentinel_proto_rawDescOnce sync.Once
	file_internal_cluster_proto_sentinel_proto_rawDescData []byte
)

func file_internal_cluster_proto_sentinel_proto_rawDescGZIP() []byte {
	file_internal_cluster_proto_sentinel_proto_rawDescOnce.Do(func() {
		file_internal_cluster_proto_sentinel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_sentinel_proto_rawDesc), len(file_internal_cluster_proto_sentinel_proto_rawDesc)))
	})
	return file_internal_cluster_proto_sentinel_proto_rawDescData
}

var file_internal_cluster_proto_sentinel_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_internal_cluster_proto_sentinel_proto_goTypes = []any{
	(*EnrollRequest)(nil),          // 0: sentinel.cluster.EnrollRequest
	(*EnrollResponse)(nil),         // 1: sentinel.cluster.EnrollResponse
	(*AgentMessage)(nil),           // 2: sentinel.cluster.AgentMessage
	(*ServerMessage)(nil),          // 3: sentinel.cluster.ServerMessage
	(*Heartbeat)(nil),              // 4: sentinel.cluster.Heartbeat
	(*ContainerInfo)(nil),          // 5: sentinel.cluster.ContainerInfo
	(*ContainerList)(nil),          // 6: sentinel.cluster.ContainerList
	(*ListContainersRequest)(nil),  // 7: sentinel.cluster.ListContainersRequest
	(*UpdateContainerRequest)(nil), // 8: sentinel.cluster.UpdateContainerRequest
	(*ContainerActionRequest)(nil), // 9: sentinel.cluster.ContainerActionRequest
	(*ContainerActionResult)(nil),  // 10: sentinel.cluster.ContainerActionResult
	(*UpdateResult)(nil),           // 11: sentinel.cluster.UpdateResult
	(*PullImageRequest)(nil),       // 12: sentinel.cluster.PullImageRequest
	(*RunHookRequest)(nil),         // 13: sentinel.cluster.RunHookRequest
	(*HookResult)(nil),             // 14: sentinel.cluster.HookResult
	(*RollbackRequest)(nil),        // 15: sentinel.cluster.RollbackRequest
	(*RollbackResult)(nil),         // 16: sentinel.cluster.RollbackResult
	(*StateReport)(nil),            // 17: sentinel.cluster.StateReport
	(*StateAck)(nil),               // 18: sentinel.cluster.StateAck
	(*PolicySync)(nil),             // 19: sentinel.cluster.PolicySync
	(*SettingsSync)(nil),           // 20: sentinel.cluster.SettingsSync
	(*OfflineJournal)(nil),         // 21: sentinel.cluster.OfflineJournal
	(*JournalEntry)(nil),           // 22: sentinel.cluster.JournalEntry
	(*CertRenewalCSR)(nil),         // 23: sentinel.cluster.CertRenewalCSR
	(*CertRenewalResponse)(nil),    // 24: sentinel.cluster.CertRenewalResponse
	nil,                            // 25: sentinel.cluster.ContainerInfo.LabelsEntry
	nil,                            // 26: sentinel.cluster.PolicySync.PoliciesEntry
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 28: google.protobuf.Duration
}
var file_internal_cluster_proto_sentinel_proto_depIdxs = []int32{
	4,  // 0: sentinel.cluster.AgentMessage.heartbeat:type_name -> sentinel.cluster.Heartbeat
	6,  // 1: sentinel.cluster.AgentMessage.container_list:type_name -> sentinel.cluster.ContainerList
	11, // 2: sentinel.cluster.AgentMessage.update_result:type_name -> sentinel.cluster.UpdateResult
	14, // 3: sentinel.cluster.AgentMessage.hook_result:type_name -> sentinel.cluster.HookResult
	16, // 4: sentinel.cluster.AgentMessage.rollback_result:type_name -> sentinel.cluster.RollbackResult
	21, // 5: sentinel.cluster.AgentMessage.offline_journal:type_name -> sentinel.cluster.OfflineJournal
	23, // 6: sentinel.cluster.AgentMessage.cert_renewal:type_name -> sentinel.cluster.CertRenewalCSR
	10, // 7: sentinel.cluster.AgentMessage.container_action_result:type_name -> sentinel.cluster.ContainerActionResult
	4,  // 8: sentinel.cluster.ServerMessage.heartbeat:type_name -> sentinel.cluster.Heartbeat
	7,  // 9: sentinel.cluster.ServerMessage.list_containers:type_name -> sentinel.cluster.ListContainersRequest
	8,  // 10: sentinel.cluster.ServerMessage.update_container:type_name -> sentinel.cluster.UpdateContainerRequest
	12, // 11: sentinel.cluster.ServerMessage.pull_image:type_name -> sentinel.cluster.PullImageRequest
	13, // 12: sentinel.cluster.ServerMessage.run_hook:type_name -> sentinel.cluster.RunHookRequest
	15, // 13: sentinel.cluster.ServerMessage.rollback:type_name -> sentinel.cluster.RollbackRequest
	19, // 14: sentinel.cluster.ServerMessage.policy_sync:type_name -> sentinel.cluster.PolicySync
	20, // 15: sentinel.cluster.ServerMessage.settings_sync:type_name -> sentinel.cluster.SettingsSync
	24, // 16: sentinel.cluster.ServerMessage.cert_renewal_response:type_name -> sentinel.cluster.CertRenewalResponse
	9,  // 17: sentinel.cluster.ServerMessage.container_action:type_name -> sentinel.cluster.ContainerActionRequest
	27, // 18: sentinel.cluster.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	25, // 19: sentinel.cluster.ContainerInfo.labels:type_name -> sentinel.cluster.ContainerInfo.LabelsEntry
	27, // 20: sentinel.cluster.ContainerInfo.created:type_name -> google.protobuf.Timestamp
	5,  // 21: sentinel.cluster.ContainerList.containers:type_name -> sentinel.cluster.ContainerInfo
	28, // 22: sentinel.cluster.UpdateResult.duration:type_name -> google.protobuf.Duration
	5,  // 23: sentinel.cluster.StateReport.containers:type_name -> sentinel.cluster.ContainerInfo
	27, // 24: sentinel.cluster.StateReport.timestamp:type_name -> google.protobuf.Timestamp
	26, // 25: sentinel.cluster.PolicySync.policies:type_name -> sentinel.cluster.PolicySync.PoliciesEntry
	28, // 26: sentinel.cluster.SettingsSync.poll_interval:type_name -> google.protobuf.Duration
	28, // 27: sentinel.cluster.SettingsSync.grace_period:type_name -> google.protobuf.Duration
	22, // 28: sentinel.cluster.OfflineJournal.entries:type_name -> sentinel.cluster.JournalEntry
	27, // 29: sentinel.cluster.JournalEntry.timestamp:type_name -> google.protobuf.Timestamp
	28, // 30: sentinel.cluster.JournalEntry.duration:type_name -> google.protobuf.Duration
	0,  // 31: sentinel.cluster.EnrollmentService.Enroll:input_type -> sentinel.cluster.EnrollRequest
	2,  // 32: sentinel.cluster.AgentService.Channel:input_type -> sentinel.cluster.AgentMessage
	17, // 33: sentinel.cluster.AgentService.ReportState:input_type -> sentinel.cluster.StateReport
	1,  // 34: sentinel.cluster.EnrollmentService.Enroll:output_type -> sentinel.cluster.EnrollResponse
	3,  // 35: sentinel.cluster.AgentService.Channel:output_type -> sentinel.cluster.ServerMessage
	18, // 36: sentinel.cluster.AgentService.ReportState:output_type -> sentinel.cluster.StateAck
	34, // [34:37] is the sub-list for method output_type
	31, // [31:34] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_internal_cluster_proto_sentinel_proto_init() }
func file_internal_cluster_proto_sentinel_proto_init() {
	if File_internal_cluster_proto_sentinel_proto != nil {
		return
	}
	file_internal_cluster_proto_sentinel_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ContainerList)(nil),
		(*AgentMessage_UpdateResult)(nil),
		(*AgentMessage_HookResult)(nil),
		(*AgentMessage_RollbackResult)(nil),
		(*AgentMessage_OfflineJournal)(nil),
		(*AgentMessage_CertRenewal)(nil),
		(*AgentMessage_ContainerActionResult)(nil),
	}
	file_internal_cluster_proto_sentinel_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Heartbeat)(nil),
		(*ServerMessage_ListContainers)(nil),
		(*ServerMessage_UpdateContainer)(nil),
		(*ServerMessage_PullImage)(nil),
		(*ServerMessage_RunHook)(nil),
		(*ServerMessage_Rollback)(nil),
		(*ServerMessage_PolicySync)(nil),
		(*ServerMessage_SettingsSync)(nil),
		(*ServerMessage_CertRenewalResponse)(nil),
		(*ServerMessage_ContainerAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_cluster_proto_sentinel_proto_rawDesc), len(file_internal_cluster_proto_sentinel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_cluster_proto_sentinel_proto_goTypes,
		DependencyIndexes: file_internal_cluster_proto_sentinel_proto_depIdxs,
		MessageInfos:      file_internal_cluster_proto_sentinel_proto_msgTypes,
	}.Build()
	File_internal_cluster_proto_sentinel_proto = out.File
	file_internal_cluster_proto_sentinel_proto_goTypes = nil
	file_internal_cluster_proto_sentinel_proto_depIdxs = nil
}
